apiVersion: 1

groups:
    -   orgId: 1
        name: infrastructure_alerts
        folder: Infrastructure
        interval: 3m
        rules:
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # RAM - WARNING
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: ram_usage_warning
                title: High RAM Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: 'clamp_min((1 - (node_memory_MemAvailable_bytes{instance="emu-node-exporter:9100", job="infrastructure"} / node_memory_MemTotal_bytes{instance="emu-node-exporter:9100", job="infrastructure"})) * 100, 0)'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [80]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Использование RAM больше 80%'
                labels:
                    severity: warning
                    component: memory

            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # RAM - CRITICAL
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: ram_usage_critical
                title: Critical RAM Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: 'clamp_min((1 - (node_memory_MemAvailable_bytes{instance="emu-node-exporter:9100", job="infrastructure"} / node_memory_MemTotal_bytes{instance="emu-node-exporter:9100", job="infrastructure"})) * 100, 0)'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [90]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Использование RAM больше 90%'
                labels:
                    severity: critical
                    component: memory

            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # CPU - WARNING
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: cpu_usage_warning
                title: High CPU Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: '100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle", instance="emu-node-exporter:9100"}[2m])))'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [80]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Загрузка CPU больше 80%'
                labels:
                    severity: warning
                    component: cpu

            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # CPU - CRITICAL
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: cpu_usage_critical
                title: Critical CPU Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: '100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle", instance="emu-node-exporter:9100"}[2m])))'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [90]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Загрузка CPU больше 90%'
                labels:
                    severity: critical
                    component: cpu

            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # DISK - WARNING
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: disk_usage_warning
                title: High Disk Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: '((node_filesystem_size_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"} - node_filesystem_avail_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"}) / node_filesystem_size_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"}) * 100'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [80]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Использование диска больше 80%'
                labels:
                    severity: warning
                    component: disk

            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            # DISK - CRITICAL
            # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            -   uid: disk_usage_critical
                title: Critical Disk Usage
                condition: C
                data:
                    -   refId: A
                        relativeTimeRange:
                            from: 300
                            to: 0
                        datasourceUid: victoria-metrics
                        model:
                            expr: '((node_filesystem_size_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"} - node_filesystem_avail_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"}) / node_filesystem_size_bytes{instance="emu-node-exporter:9100", job="infrastructure", mountpoint="/", fstype!="rootfs"}) * 100'
                            refId: A

                    -   refId: B
                        datasourceUid: __expr__
                        model:
                            type: reduce
                            expression: A
                            reducer: last
                            refId: B

                    -   refId: C
                        datasourceUid: __expr__
                        model:
                            type: threshold
                            expression: B
                            conditions:
                                -   evaluator:
                                        params: [90]
                                        type: gt
                                    type: query
                            refId: C

                noDataState: NoData
                execErrState: Error
                for: 3m
                annotations:
                    description: 'Использование диска больше 90%'
                labels:
                    severity: critical
                    component: disk