x-logging: &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

networks:
    net:
        name: net
        driver: bridge

services:
    emu-backend-postgres:
        image: postgres:17.6
        container_name: "${EMU_BACKEND_POSTGRES_CONTAINER_NAME}"
        volumes:
            - "../${EMU_BACKEND_POSTGRES_VOLUME_DIR}:/var/lib/postgresql/data"
        ports:
            - "${EMU_BACKEND_POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: "${EMU_BACKEND_POSTGRES_DB_NAME}"
            POSTGRES_USER: "${EMU_BACKEND_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${EMU_BACKEND_POSTGRES_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    emu-monitoring-redis:
        image: redis:8.0.2
        container_name: "${EMU_MONITORING_REDIS_CONTAINER_NAME}"
        volumes:
            - "../${EMU_MONITORING_REDIS_CONFIG_FILE}:/etc/redis/redis.conf"
            - "../${EMU_MONITORING_REDIS_VOLUME_DIR}:/data"
        ports:
            - "${EMU_MONITORING_REDIS_PORT}:6379"
        command: "redis-server /etc/redis/redis.conf"
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    emu-loki:
        image: grafana/loki:3.5.1
        container_name: "${EMU_LOKI_CONTAINER_NAME}"
        volumes:
            - "../${EMU_LOKI_CONFIG_FILE}:/etc/loki/loki.yaml:ro"
            - "../${EMU_LOKI_VOLUME_DIR}:/loki"
        ports:
            - "${EMU_LOKI_HTTP_PORT}:${EMU_LOKI_HTTP_PORT}"
            - "${EMU_LOKI_GRPC_PORT}:${EMU_LOKI_GRPC_PORT}"
        command: [ "-config.file=/etc/loki/loki.yaml" ]
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    emu-tempo:
        image: grafana/tempo:2.7.2
        container_name: "${EMU_TEMPO_CONTAINER_NAME}"
        volumes:
            - "../${EMU_TEMPO_CONFIG_FILE}:/etc/tempo/tempo.yaml:ro"
            - "../${EMU_TEMPO_VOLUME_DIR}:/var/tempo"
        ports:
            - "${EMU_TEMPO_HTTP_PORT}:${EMU_TEMPO_HTTP_PORT}"
            - "${EMU_TEMPO_GRPC_PORT}:${EMU_TEMPO_GRPC_PORT}"
            - "${EMU_TEMPO_OTLP_HTTP_PORT}:${EMU_TEMPO_OTLP_HTTP_PORT}"
            - "${EMU_TEMPO_OTLP_GRPC_PORT}:${EMU_TEMPO_OTLP_GRPC_PORT}"
        command: [ "-config.file=/etc/tempo/tempo.yaml" ]
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    emu-victoria-metrics:
        image: victoriametrics/victoria-metrics:v1.118.0
        container_name: "${EMU_VICTORIA_METRICS_CONTAINER_NAME}"
        volumes:
            - "../${EMU_VICTORIA_METRICS_VOLUME_DIR}:/victoria-metrics-data"
        ports:
            - "${EMU_VICTORIA_METRICS_HTTP_PORT}:${EMU_VICTORIA_METRICS_HTTP_PORT}"
        command:
            - '-storageDataPath=/victoria-metrics-data'
            - '-retentionPeriod=30d'
            - '-httpListenAddr=:8428'
            - '-memory.allowedPercent=80'
            - '-search.maxUniqueTimeseries=1000000'
            - '-search.maxQueryDuration=120s'
        logging: *default-logging
        restart: unless-stopped
        networks:
            - net

    emu-weed-master:
        image: chrislusf/seaweedfs
        logging: *default-logging
        container_name: emu-weed-master
        ports:
            - "${EMU_WEED_MASTER_PORT}:${EMU_WEED_MASTER_PORT}"
        command: "master"
        networks:
            - net

    emu-weed-volume:
        image: chrislusf/seaweedfs:latest
        container_name: emu-weed-volume
        command: >
            volume 
            -mserver="${EMU_WEED_MASTER_CONTAINER_NAME}:${EMU_WEED_MASTER_PORT}" 
            -ip.bind=0.0.0.0 
            -port=8080 
            -dir="/data"
            -max=10
            -metricsPort=9325
            -dataCenter=dc1
            -rack=rack2
        volumes:
            - "../${EMU_WEED_VOLUME_DIR}:/data"
        depends_on:
            - emu-weed-master
        networks:
            - net
        restart: unless-stopped
        logging: *default-logging

    emu-weed-filer:
        image: chrislusf/seaweedfs:latest
        container_name: emu-weed-filer
        command: >
            filer 
            -master="${EMU_WEED_MASTER_CONTAINER_NAME}:${EMU_WEED_MASTER_PORT}"
            -ip.bind=0.0.0.0 
            -metricsPort=9327
        depends_on:
            - emu-weed-master
            - emu-weed-volume
        networks:
            - net
        restart: unless-stopped
        logging: *default-logging