apiVersion: 1

datasources:
    -   name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://emu-victoria-metrics:8428
        uid: victoria-metrics
        isDefault: true
        editable: true
        jsonData:
            timeInterval: "5s"
            queryTimeout: "300s"
            httpMethod: POST

    -   name: Tempo
        type: tempo
        access: proxy
        url: http://emu-tempo:3200
        uid: tempo
        editable: true
        jsonData:
            httpMethod: GET
            nodeGraph:
                enabled: true
            search:
                hide: false
            spanBar:
                type: 'Tag'
                tag: 'http.status_code'

    -   name: Loki
        type: loki
        url: http://emu-loki:3100
        uid: loki